---
title: "The _methyvim_ R Package"
subtitle: "Data-Adaptive Estimation and Inference for Targeted Differential
  Methylation Analysis"
author: "[Nima Hejazi](https://statistics.berkeley.edu/~nhejazi)
  \nGroup in Biostatistics, and
  \nCenter for Computational Biology
  \nUniversity of California, Berkeley"
date: "`r lubridate::now()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: xaringan-themer.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      navigation: {
        scroll: false
      }
---

```{r knitr_setup, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.width = 7, fig.height = 4.5, dpi = 300,
                      fig.cap = "", fig.align = "center")
showtext::showtext_opts(dpi = 300)
```

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r xaringan-themer, include = FALSE}
library(xaringanthemer)
solarized_light(
  #base_color = "#1c5253",
  header_font_google = google_font("Josefin Sans"),
  text_font_google = google_font("Montserrat", "300", "300i"),
  code_font_google = google_font("Droid Mono")
)
```

# Differential methylation

